# 项目内错误处理

[TOC]



### goroutine中panic

goroutine 中的 panic 无法被外围的 recover 捕获。

创建 goroutine 使用基础中创建 goroutine 的基础方法，防止意外退出。在新创建的 goroutine 中增加 recover 逻辑。

```go
// 创建 goroutine 的公共方法
func G(a int, f func(x int)) {
   go func() {
      defer func() {
         if err := recover(); err != nil {
            log.Println("Get a panic: ", err)
         }
      }()
      f(a)
   }()
}

func g3() {
   // 模拟数组越界
   fx := func(i int) {
      a := make([]int, 0, 3)
      a[i] = i
   }

   G(8, fx)
   time.Sleep(3 * time.Second)
}
```

### 错误处理

**业务代码少用 sentinel error**

sentinel error：包级别与定义的错误类型。如 io.EOF。使用 sentinel 值是最不灵活的错误处理策略，因为调用方必须使用 `==` 将结果与预先声明的值进行比较。

- Sentinel errors  不好添加上下文，额外信息时，不够灵活, 
- Sentinel errors 在两个包之间创建了依赖。
- 业务代码，不推荐过多使用 sentinel errors。



**自定义错误结构体类型**

调用者可以使用`断言`转换成这个类型，来获取更多的上下文信息。 就要让自定义的 *error* 变为 public。这种模型会导致和调用者产生强耦合，从而导致 API 变得脆弱。

因此，还是建议是避免错误类型，或者至少避免将它们作为公共 API 的一部分。



#### 推荐使用 Opaque error

定义一个接口，内嵌 error 接口，并通过自定义 方法扩展添加错误类型。把更多的错误判断信息隐藏在内部，只对外暴露 true 和 false 和响应的判断错误的方法。

以 os.net 包 net.go 为例：

```go
// An Error represents a network error. 
type Error interface {
   error
   Timeout() bool   // Is the error a timeout?
   Temporary() bool // Is the error temporary?
}

type OpError struct {
	Op string
	Net string
  
	Source Addr
	Addr Addr
	Err error
}

func (e *OpError) Unwrap() error { return e.Err }

func (e *OpError) Error() string {}

type timeout interface {
	Timeout() bool
}
// 是否超时错误的逻辑在包内不，保外调用即可，最终向包外只暴露一个方法，和一个 判断结果 true false
func (e *OpError) Timeout() bool {
	if ne, ok := e.Err.(*os.SyscallError); ok {
		t, ok := ne.Err.(timeout)
		return ok && t.Timeout()
	}
	t, ok := e.Err.(timeout)
	return ok && t.Timeout()
}

type temporary interface {
	Temporary() bool
}

func (e *OpError) Temporary() bool {
	// Treat ECONNRESET and ECONNABORTED as temporary errors when
	// they come from calling accept. See issue 6163.
	if e.Op == "accept" && isConnError(e.Err) {
		return true
	}

	if ne, ok := e.Err.(*os.SyscallError); ok {
		t, ok := ne.Err.(temporary)
		return ok && t.Temporary()
	}
	t, ok := e.Err.(temporary)
	return ok && t.Temporary()
}

// 使用
if ne, ok := err.(net.Error); ok && cr.aborted && ne.Timeout() {
  // Ignore this error. It's the expected error from
  // another goroutine calling abortPendingRead.
} else if err != nil {
  cr.handleReadError(err)
}
// 使用
if ne, ok := e.(net.Error); ok && ne.Temporary() {
  
}

```

调用方使用

```go
func (c *Conn) readRecordOrCCS(expectChangeCipherSpec bool) error {
  ...
	// Read header, payload.
	if err := c.readFromUntil(c.conn, recordHeaderLen); err != nil {
    if err == io.ErrUnexpectedEOF && c.rawInput.Len() == 0 {
			err = io.EOF
		}
		if e, ok := err.(net.Error); !ok || !e.Temporary() {
			c.in.setErrorLocked(err)
		}
		return err
  }
  ...
}  
```



这种方式最大的好处就是，错误信息被隐藏，调用方的错误类型判断都在提供方实现，避免了类似 err == ErrNotFound 的判断逻辑，这种方式会造成比较强的依赖关系，不利于扩展。

其核心细想就是*减少依赖面积*，这个在 k8s，os.net 等开源代码中也很常见。



#### 使用errors.Wrap 处理错误

在多个函数调用时，通过 `fmt.Errorf` 的方式处理错误会导致除了错误文本信息之外的堆栈信息对丢，不易于问题排查。

```go
fmt.Errorf("ScanFileFailed : %v", err) //导致堆栈信息丢失
```

可以通过 `github.com/pkg/errors` 包中的 errors.Wrap, errors.Unwrap, errors.Cause, 等方法处理错误，可在多层调用时追加额外的错误信息，夜可以还原错误对战信息。



```go
func ScanFile() {
   if err := biz.ScanFile(); err != nil {
      fmt.Println("Unwrap :", errors.Unwrap(err))
      fmt.Println("Cause :", errors.Cause(err))
      fmt.Printf("stack trace: %+v\n", err)
   }
}

// 打开一个文件，打印楚文件内容，如果出错，返回错误信息
func ScanFile() error {
	if err := openFile(); err != nil {
		//return fmt.Errorf("ScanFileFailed : %v", err)
		return errors.Wrap(err, "scan file failed")
	}
	return nil
}


func openFile() error {
	var err error
	var str string
	f, err := os.Open("./test1.log")
	defer f.Close()
	if err != nil {
		//return fmt.Errorf("CanNotOpenFile : %v", err)
		return errors.Wrap(err, "CanNotOpenFile")
	}
	sc := bufio.NewReader(f)

	for err == nil {
		str, err = sc.ReadString('\n')
		fmt.Print(str)
	}

	if err == io.EOF {
		return nil
	}

	return err
}
```

输出：

```
Unwrap : scan file failed: CanNotOpenFile: open ./test1.log: no such file or directory
Cause : open ./test1.log: no such file or directory
stack trace: open ./test1.log: no such file or directory
CanNotOpenFile
...
```

- `errors.Wrap()`, 可以对收到的错误信息，进一步包装，添加额外的描述；但是不会导致的堆栈信息丢失
- `errors.Unwrap()`,剥开包装，拿到带有额外描述的错误描述信息
- `errors.Cause()`, 得到导致错误的描述信息，即 root error

**errors.Wrap()的使用建议**

如果和其他库进行协作，考虑使用 errors.Wrap 或者 errors.Wrapf 保存堆栈信息。同样适用于和标准库协作的时候。 

```go
f, err := os.Open("./test1.log")
defer f.Close()
if err != nil {
   return errors.Wrap(err, "CanNotOpenFile")
}
```

直接返回错误，而不是每个错误产生的地方到处打日志。

建议在程序的顶部或者是工作的 goroutine 顶部(请求入口)，使用 *%+v* 把堆栈详情记录。比如在 web 框架中，会有中间件专门对 panic ， recover 进行处理的。可以在这统一处理。

errors.Wrap() 通常在应用代码中使用，在一些基础库中，直接返回根错误，不做额外的处理，Wrap error 的操作留给业务调用方法处理。

如果在应用代码中，不打算处理错误，就直接用 errors.Wrap 包装错误，直接返回。

*错误只应该被处理一次*，一旦错误被处理了，比如返回降级数据时，那么 error 就应该以 nil 的形式返回给上一层。



### 错误处理用法建议

- error.Error() 只是为了方便开发调试，不作为常规判断错误依据。
- 无错误的正常流程代码，将成为一条直线，而不是缩进的代码。
- 避免多余的包装判断。

- 在应用代码中使用 errors.New()，errors.Errorf() 根据描述信息生成一个 error 对象，同时自动会记录堆栈信息。
- 如果是调用自己项目内的其他方法返回的 err， 则直接透传返回 err
- errors.Wrap() 一次错误链中，只使用一次，因为每次调用都会让堆栈信息加倍增加。即重复了。
- 如果和其他第三方库进行协作，如标准库，git 上其他库，公司基础库，建议使用 errors.Wrap 或者 errors.Wrapf 保存堆栈信息（root error），上层再调用直接 error ，不再 wrap。
- 基础库只返回 root error ，不做 Wrap error 处理
- 对于api接口，如果 reponse 不是必须的排查错误必须的，不建议打印出来，因为这个通常会比较大。
- 对于基础库适当使用 sentinel error 的错误也是可以的。

